'use client'

import './globals.css'
import { useState } from 'react'
import { PortionsProvider } from './context/portions-context'
import { MealsProvider } from './context/meals-context'
import { NavBar } from './layout/nav/nav-bar'
// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout(props: LayoutProps) {
  const [menuOpen, setMenuOpen] = useState(false)

  return (
    <html lang="en">
      <body className={menuOpen ? "menu-open" : ''}>
        <NavBar onclick={() => setMenuOpen(!menuOpen)}/>
        <PortionsProvider>
          <MealsProvider>
            {props.children}
          </MealsProvider>
        </PortionsProvider>
      </body>
    </html>
  )
}

export interface LayoutProps {
  children: React.ReactNode
}


