import './globals.css'
import { PortionsProvider } from './context/portions-context'
import { MealsProvider } from './context/meals-context'
import { NavBar } from './layout/nav/nav-bar'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar/>
        <PortionsProvider>
          <MealsProvider>
            {children}
          </MealsProvider>
        </PortionsProvider>
      </body>
    </html>
  )
}
